# Generated by Django 4.2.4 on 2023-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
    ]
