# Generated by Django 4.2.4 on 2023-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_book_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="English", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="language",
        ),
    ]
