# Generated by Django 4.2.4 on 2023-08-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_language_remove_book_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                default="English",
                help_text="Select the language this book was written in",
                max_length=50,
                to="catalog.language",
            ),
        ),
    ]
