# Generated by Django 4.2.4 on 2023-10-03 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0004_book_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="borrower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                help_text="Select the language this book was written in",
                to="catalog.language",
            ),
        ),
    ]
